# Generated by Django 5.2 on 2025-04-14 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('corresponding', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Pharmacy', 'Pharmacy'), ('Management', 'Management'), ('Physics', 'Physics'), ('Applied Chemistry', 'Applied Chemistry'), ('Applied Mathematics', 'Applied Mathematics'), ('Applied Science', 'Applied Science'), ('Sports', 'Sports'), ('Physical Education', 'Physical Education'), ('Yoga', 'Yoga'), ('Physiotherapy', 'Physiotherapy'), ('Agriculture', 'Agriculture'), ('Legal Education', 'Legal Education'), ('Medical Research', 'Medical Research'), ('Clinical Research', 'Clinical Research'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Computer Engineering', 'Computer Engineering'), ('Software Engineering', 'Software Engineering')], max_length=50)),
                ('description', models.TextField()),
                ('issn', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField()),
                ('keywords', models.TextField(help_text='One keyword per line')),
                ('paper_file', models.FileField(upload_to='submissions/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revisions_required', 'Revisions Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='submitted', max_length=20)),
                ('revision_notes', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='main.author')),
                ('corresponding_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corresponding_submissions', to='main.author')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.journal')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
