# Generated by Django 5.2 on 2025-04-21 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('about', models.TextField(blank=True)),
                ('aim_scope', models.TextField(blank=True)),
                ('call_for_papers', models.TextField(blank=True)),
                ('author_guidelines', models.TextField(blank=True)),
                ('editorial_board', models.TextField(blank=True)),
                ('archive_info', models.TextField(blank=True)),
                ('indexes', models.TextField(blank=True)),
                ('downloads_info', models.TextField(blank=True)),
                ('contact_us', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journal_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='JournalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_factor', models.FloatField(blank=True, null=True)),
                ('issn', models.CharField(blank=True, max_length=20)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.journal')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=200)),
                ('paper_file', models.FileField(upload_to='submissions/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='submission_covers/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('authors', models.ManyToManyField(related_name='submissions', to='main.author')),
                ('corresponding_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corresponding_submissions', to='main.author')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.journal')),
            ],
        ),
    ]
