# Generated by Django 5.2 on 2025-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=100)),
                ('author_info', models.TextField()),
                ('keywords', models.CharField(max_length=200)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='corresponding_author',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submitted_by',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
