# Generated by Django 5.2 on 2025-04-18 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalDetail',
            fields=[
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='main.journal')),
                ('about', models.TextField(blank=True, default='About this journal...')),
                ('aim_scope', models.TextField(blank=True, default='Journal aims and scope...')),
                ('call_for_papers', models.TextField(blank=True, default='Call for papers information...')),
                ('author_guidelines', models.TextField(blank=True, default='Author submission guidelines...')),
                ('editorial_board', models.TextField(blank=True, default='Editorial board members...')),
                ('indexes', models.TextField(blank=True, default='Indexing information...')),
                ('contact_info', models.TextField(blank=True, default='Contact details...')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Detail',
                'verbose_name_plural': 'Journal Details',
            },
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='journalindex',
            name='journal',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='submittedpaper',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Submitted Paper', 'verbose_name_plural': 'Submitted Papers'},
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='main_journa_journal_ac59af_idx',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='main_journa_status_59be4b_idx',
        ),
        migrations.RenameField(
            model_name='submittedpaper',
            old_name='modified_date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='department',
        ),
        migrations.RemoveField(
            model_name='author',
            name='orcid_id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='order',
        ),
        migrations.RemoveField(
            model_name='author',
            name='position',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='about',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='aim_scope',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='author_guidelines',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='call_for_papers',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='editor_in_chief',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='eissn',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='journal_type',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='reach_us',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='submittedpaper',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='submittedpaper',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='submittedpaper',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='submittedpaper',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submittedpaper',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='submittedpaper',
            name='title',
        ),
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='code',
            field=models.CharField(choices=[('PHARM', 'Pharmacy'), ('MGMT', 'Management'), ('PHYS', 'Physics'), ('CHEM', 'Applied Chemistry'), ('MATH', 'Applied Mathematics'), ('SCI', 'Applied Science'), ('SPORT', 'Sports'), ('PE', 'Physical Education'), ('YOGA', 'Yoga'), ('PHYSIO', 'Physiotherapy'), ('AGRI', 'Agriculture'), ('LAW', 'Legal Education'), ('MED', 'Medical Research'), ('CLIN', 'Clinical Research'), ('MECH', 'Mechanical Engineering'), ('EEE', 'Electrical Engineering'), ('CSE', 'Computer Engineering')], default=django.utils.timezone.now, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittedpaper',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_covers/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='submittedpaper',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='paper_covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='submittedpaper',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_papers', to='main.journal'),
        ),
        migrations.AlterField(
            model_name='submittedpaper',
            name='upload',
            field=models.FileField(upload_to='papers/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='EditorialMember',
        ),
        migrations.DeleteModel(
            name='JournalIndex',
        ),
    ]
