# Generated by Django 5.2 on 2025-04-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='corresponding_author',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='journaldetail',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='journal',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='is_published',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='about',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='aim_scope',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='archive_info',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='author_guidelines',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='call_for_papers',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='contact_us',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='downloads_info',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='editorial_board',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='indexes',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='JournalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('pdf_file', models.FileField(upload_to='papers/')),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('about', models.TextField()),
                ('aim_scope', models.TextField()),
                ('call_for_papers', models.TextField()),
                ('author_guidelines', models.TextField()),
                ('editorial_board', models.TextField()),
                ('archive', models.TextField()),
                ('indexes', models.TextField()),
                ('downloads', models.FileField(upload_to='downloads/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.journal')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='JournalDetail',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
