# Generated by Django 5.2 on 2025-04-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_submission_corresponding_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalsubmission',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='journalsubmission',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='journalsubmission',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
    ]
