# Generated by Django 5.2 on 2025-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_submittedpaper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedpaper',
            name='journal',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('DS', 'Data Science'), ('SE', 'Software Engineering'), ('BIO', 'Bioinformatics')], max_length=100),
        ),
    ]
