# Generated by Django 5.2 on 2025-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_journaldetail_remove_editorialmember_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpaper',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
