# Generated by Django 5.2 on 2025-04-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_submittedpaper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpaper',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submittedpaper',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
