# Generated by Django 5.2 on 2025-04-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_submittedpaper_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedpaper',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
