# Generated by Django 5.2 on 2025-05-05 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_journalsubmission_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('brochure', models.FileField(blank=True, null=True, upload_to='conference_brochures/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('submitter_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='journalsubmission',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='journal',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalsubmission',
            name='paper_file',
            field=models.FileField(default=1, upload_to='papers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalsubmission',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalsubmission',
            name='aim_scope',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalsubmission',
            name='archive',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalsubmission',
            name='author_guidelines',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalsubmission',
            name='call_for_papers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalsubmission',
            name='downloads',
            field=models.FileField(blank=True, upload_to='downloads/'),
        ),
        migrations.AlterField(
            model_name='journalsubmission',
            name='editorial_board',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalsubmission',
            name='indexes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalsubmission',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
