# Generated by Django 5.2 on 2025-05-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_conferencesubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalsubmission',
            name='paper_file',
        ),
    ]
