# Generated by Django 5.2 on 2025-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_submittedpaper_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedpaper',
            name='upload',
            field=models.FileField(upload_to='papers/'),
        ),
    ]
