# Generated by Django 5.2 on 2025-04-18 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_submittedpaper_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaldetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journaldetail',
            name='journal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='main.journal'),
        ),
    ]
