# Generated by Django 5.2 on 2025-04-15 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_submittedpaper_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedpaper',
            name='author_info',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom')], max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('is_corresponding', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='main.submittedpaper')),
            ],
        ),
    ]
