# Generated by Django 5.2 on 2025-04-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_submittedpaper_author_info_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpaper',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='submittedpaper',
            name='upload',
            field=models.FileField(upload_to='papers/'),
        ),
    ]
