# Generated by Django 5.2 on 2025-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_submittedpaper_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedpaper',
            name='journal',
            field=models.CharField(choices=[('PHARM', 'Pharmacy'), ('MGMT', 'Management'), ('PHYS', 'Physics'), ('CHEM', 'Applied Chemistry'), ('MATH', 'Applied Mathematics'), ('SCI', 'Applied Science'), ('SPORT', 'Sports'), ('PE', 'Physical Education'), ('YOGA', 'Yoga'), ('PHYSIO', 'Physiotherapy'), ('AGRI', 'Agriculture'), ('LAW', 'Legal Education'), ('MED', 'Medical Research'), ('CLIN', 'Clinical Research'), ('MECH', 'Mechanical Engineering'), ('EEE', 'Electrical Engineering'), ('CSE', 'Computer Engineering')], max_length=100),
        ),
    ]
