# Generated by Django 5.2 on 2025-04-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_submittedpaper_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.TextField()),
                ('abstract', models.TextField()),
                ('conference_date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='proceedings/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
